### ISSUE TITLE
Problem in install

### ISSUE THREAD

**Issue by sunftec** [sadovojav/yii2-image-thumbnail#1]
hi. thank you for this.i am a first watcher !
but i cant install with composer! how to install manually?

**Comment by sadovyiov** [comment]
Hi. What trouble do you have?
I checked. The composer set correctly.
If you can, post your screen

Try to install manualy:
1 Download latest version - https://github.com/sadovojav/yii2-image-thumbnail/archive/master.zip
2 Unzip and upload it `vendor/sadovojav/yii2-image-thumbnail`
3 Add to `vendor\yiisoft\extensions.php`:

``` php
  'sadovojav/yii2-image-thumbnail' => 
  array (
    'name' => 'sadovojav/yii2-image-thumbnail',
    'version' => '9999999-dev',
    'alias' => 
    array (
      '@sadovojav/image' => $vendorDir . '/sadovojav/yii2-image-thumbnail',
    ),
  ),
```

4 Add to `vendor/composer/autoload_psr4.php`:

``` php
'sadovojav\\image\\' => array($vendorDir . '/sadovojav/yii2-image-thumbnail'),
```

5 Add to config this component

**Comment by sunftec** [comment]
thank you
![untitled](https://cloud.githubusercontent.com/assets/10174535/8546405/6a012b06-246c-11e5-8063-51ba200075b6.png)

**Comment by sadovyiov** [comment]
Watch your composer.json and add this two rows:

```
"minimum-stability": "dev",
"prefer-stable": true,
```

I think, you have a problem with pendalf89/yii2-filemanager. Those two lines have to solve the problem
