### ISSUE TITLE
PLACEHOLDER_TYPE_URL broken (http://placeholdit.imgix.net/ no longer reachable)

### ISSUE THREAD

**Issue by h0lg** [sadovojav/yii2-image-thumbnail#10]
http://placeholdit.imgix.net/ seems to have moved, so the placeholder type PLACEHOLDER_TYPE_URL is no longer working.

**Comment by sadovyiov** [comment]
Fixed: https://github.com/sadovojav/yii2-image-thumbnail/commit/6eb00e4ba72437e4658dfb8abdfd7b45057a8049

**Comment by h0lg** [comment]
Good stuff, dude! Thanks heaps <3
