### ISSUE TITLE
problem with work

### ISSUE THREAD

**Issue by sunftec** [sadovojav/yii2-image-thumbnail#2]
![untitled](https://cloud.githubusercontent.com/assets/10174535/8547039/f727245a-2470-11e5-96d1-c7d528e02287.png)

after install and config i cant use this..

**Comment by sadovyiov** [comment]
Wrong second parameter. It must be array

``` php
echo Yii::$app->thumbnail->url(YOUR_URL, [
    'resize' => [
        'width' => 320,
        'height' => 200
    ]
]);
```

For example, I use this:

``` php
<?= Yii::$app->thumbnail->img($value->image, [
    'thumbnail' => [
        'width' => 320,
        'height' => 230,
    ],
    'placeholder' => [
        'width' => 320,
        'height' => 230
    ]
]); ?>
```

**Comment by sunftec** [comment]
i try this:
<code>
Yii::$app->thumbnail->img('@web/uploads/dd.jpg', [
                        'thumbnail' => [
                            'width' => 400,
                            'height' => 400,
                        ],
                        'placeholder' => [
                            'width' => 320,
                            'height' => 230
                        ]
                    ]);
</code>

but  i see oops image!! not resize an show dd,jpg

**Comment by sadovyiov** [comment]
Try this in first parameter:
Yii::getAlias('@web/uploads/dd.jpg') or '/uploads/dd.jpg'

**Comment by sunftec** [comment]
Again i see oops image

**Comment by sadovyiov** [comment]
Can you show me full path from dd.jpg, and config this component. I think, that the problem is exactly on image path.
Please, see basePath component parameter. Default: @webroot (in README this line is wrong)

**Comment by sunftec** [comment]
<code>
$config = [
    'id' => 'basic',
        'language' => 'en',
    'basePath' => dirname(**DIR**),
    'bootstrap' => ['log' , 'thumbnail'
    ],

```
'components' => [

        'thumbnail' => [
                'class' => 'sadovojav\image\Thumbnail',
        ],
```

</code>

**Comment by sadovyiov** [comment]
Give me full path from dd.jpg.
I want to help you, but i need more information.
By default (basePath) your upload directory should be placed in "web": `/web/uploads`
You can try this src, if your uploads directory in root `/uploads` 

``` php
 echo Yii::$app->thumbnail->img('../uploads/dd.jpg', [
     'thumbnail' => [
        'width' => 400,
        'height' => 400
     ], 
     'placeholder' => [
         'width' => 320,
         'height' => 230
     ]
 ]); 
```

**Comment by sunftec** [comment]
thank you for help me.
my image path :
<code>
http://localhost/websitnews/web/uploads/dd.jpg
</code>

**Comment by sadovyiov** [comment]
Please show me result this code:

``` php
echo Yii::getAlias('@webroot');
```

**Comment by sunftec** [comment]
ok!sorry...
it :<code> C:/Program Files (x86)/Ampps/www/websitnews/web  
</code>

**Comment by sadovyiov** [comment]
Hmmm...
Then the src must be: `'/uploads/dd.jpg'` if it file are located there `http://localhost/websitnews/web/uploads/dd.jpg`
Maybe space in the path wrong handled.
I will try to reproduce your case.

**Comment by sunftec** [comment]
i have a lot space on this directory.. thank you for all answers..

**Comment by sadovyiov** [comment]
@sunftec Hi.I've reproduced your situation, but got a different result.
I replace string (line 240 (v2.0)/line 200 (v1.0)).
from:  `php $file = FileHelper::normalizePath(Yii::getAlias($this->basePath . '/' . $file));`
to: `php``$file = FileHelper::normalizePath($file);```

``` php
  echo '@webroot: -' . Yii::getAlias("@webroot") . '<br/>';

         $src = 'C:/Program Files (x86)/Ampps/domains/test/frontend/web/uploads/dir (with) space/dd.jpg';

         echo 'src - ' . $src . '<br/>';;

         echo Yii::$app->thumbnail->img($src, [
             'thumbnail' => [
                'width' => 400,
                'height' => 400
             ], 
             'placeholder' => [
                 'width' => 320,
                 'height' => 230
             ]
         ]); 

        die();
```

Result:
![untitled-1](https://cloud.githubusercontent.com/assets/9282021/8569904/fd1e576a-2584-11e5-8c01-0e2787f36d6d.jpg)

Try to do as well, with full path to image.
